# docker-compose.yml

version: '3.8'

services:
  museum-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: museum-backend
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - BIND_ADDRESS={BIND_ADDRESS}
      - DB_USER={DB_USER}
      - DB_PASSWORD={DB_PASSWORD}
      - DB_NAME={DB_NAME}
      - DB_HOST={DB_HOST}
      - DB_PORT={DB_PORT}
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    